name: PR Status Check for Promotion/QA

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - promotion/qa

jobs:
  validate-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Check Code Analysis Status
        id: code-analysis-check
        run: |
          # Check if code analysis job has completed and passed
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"
          
          # Get the latest workflow run for this PR
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/actions/runs?event=pull_request&head_sha=${{ github.event.pull_request.head.sha }}")
          
          # Check if code-analysis job passed
          CODE_ANALYSIS_PASSED=$(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[] | select(.name=="Compile and Publish AL Application Workflow") | .jobs_url' | xargs -I{} \
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" {} | \
            jq -r '.jobs[] | select(.name=="code-analysis") | .conclusion')
          
          if [ "$CODE_ANALYSIS_PASSED" == "success" ]; then
            echo "Code analysis passed"
            exit 0
          else
            echo "Code analysis must pass before this PR can be merged"
            exit 1
          fi
        shell: bash